### ISSUE TITLE
Cant install Rmagick 2.13.4 on Macosx, newer version is compatible?

### ISSUE THREAD

**Issue by silentwarrior** [rktjmp/tileup#8]
Hello.

I cant install Rmagick 2.13.4 on Macosx, a newer version works just fine, like v2.15.4 :
sudo gem install rmagick 
but not 
sudo gem install rmagick --version 2.13.4

When trying to install tileup via 'gem install tileup' it will try and install version 2.13.4 of rmagick, failing everytime.

Can you bump the version number for rmagick?

PS: cloned on my system, bumped the version up to 2.15.4, built the gem and installed it, worked perfectly. Oh btw, its damn fast too, thank you :)

**Comment by rktjmp** [comment]
Sorry, currently overseas without access to a development machine. I think
you will have to git clone the project, edit the gem file then I think you
can point gem to install from a local directory.

**Comment by rktjmp** [comment]
Thanks for the heads up, the version requirements were needlessly specific. I have pushed a new fix to ruby gems. I hope `tileup` was useful for you.
